/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latihan2_Part2;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author H4NS
 */
public class Latihan2 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan2
     */
    public Latihan2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Awalan = new javax.swing.JLabel();
        NAMA = new javax.swing.JLabel();
        KELAS = new javax.swing.JLabel();
        ALAMAT = new javax.swing.JLabel();
        SEKOLAH = new javax.swing.JLabel();
        TANAM = new javax.swing.JTextField();
        TKELAS = new javax.swing.JComboBox<>();
        TALAMAT = new javax.swing.JTextField();
        TSEKOLAH = new javax.swing.JTextField();
        TAMBAH = new javax.swing.JButton();
        KELUAR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        Awalan.setFont(new java.awt.Font("Monospaced", 3, 26)); // NOI18N
        Awalan.setForeground(new java.awt.Color(255, 255, 255));
        Awalan.setText("TABEL BIODATA");

        NAMA.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        NAMA.setForeground(new java.awt.Color(255, 255, 255));
        NAMA.setText("NAMA");

        KELAS.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        KELAS.setForeground(new java.awt.Color(255, 255, 255));
        KELAS.setText("KELAS");

        ALAMAT.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        ALAMAT.setForeground(new java.awt.Color(255, 255, 255));
        ALAMAT.setText("ALAMAT");

        SEKOLAH.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        SEKOLAH.setForeground(new java.awt.Color(255, 255, 255));
        SEKOLAH.setText("SEKOLAH");

        TKELAS.setBackground(new java.awt.Color(255, 51, 51));
        TKELAS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XI RPL  1", "XI RPL  2", "XI RPL  3", "XI RPL  4", "XI RPL  5", "XI RPL  6", "XI RPL  7", "XI TKJ  1", "XI TKJ  2", "XI TKJ  3", "XI TKJ  4", "XI TKJ  5", "XI TKJ  6", " " }));

        TAMBAH.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        TAMBAH.setText("ADD");
        TAMBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAMBAHActionPerformed(evt);
            }
        });

        KELUAR.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        KELUAR.setText("EXIT");
        KELUAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KELUARActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Kelas", "Alamat", "Sekolah"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(Awalan))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SEKOLAH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TSEKOLAH, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(ALAMAT)
                                    .addGap(18, 18, 18)
                                    .addComponent(TALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(NAMA)
                                        .addComponent(KELAS))
                                    .addGap(25, 25, 25)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TANAM)
                                        .addComponent(TKELAS, 0, 239, Short.MAX_VALUE)))))
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TAMBAH)
                            .addComponent(KELUAR)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Awalan)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NAMA)
                    .addComponent(TANAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KELAS)
                    .addComponent(TKELAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TAMBAH))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KELUAR)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ALAMAT)
                            .addComponent(TALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SEKOLAH)
                            .addComponent(TSEKOLAH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 910, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TAMBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAMBAHActionPerformed
        // TODO add your handling code here:
        String NAMA = TANAM.getText();
        String KELAS = TKELAS.getSelectedItem().toString();
        String ALAMAT = TALAMAT.getText();
        String SEKOLAH = TSEKOLAH.getText();
        
        if(TKELAS.getSelectedItem()=="XI RPL 1"){
        } if(TKELAS.getSelectedItem()=="XI RPL 2"){
        } if(TKELAS.getSelectedItem()=="XI RPL 3"){
        } if(TKELAS.getSelectedItem()=="XI RPL 4"){
        } if(TKELAS.getSelectedItem()=="XI RPL 5"){
        } if(TKELAS.getSelectedItem()=="XI RPL 6"){
        } if(TKELAS.getSelectedItem()=="XI RPL 7"){
        }if(TKELAS.getSelectedItem()=="XI TKJ 1"){
        }if(TKELAS.getSelectedItem()=="XI TKJ 2"){
        }if(TKELAS.getSelectedItem()=="XI TKJ 3"){
        }if(TKELAS.getSelectedItem()=="XI TKJ 4"){
        }if(TKELAS.getSelectedItem()=="XI TKJ 5"){
        }if(TKELAS.getSelectedItem()=="XI TKJ 6"){
        }
        DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[]{TANAM.getText(),TKELAS.getSelectedItem(),TALAMAT.getText(),
        TSEKOLAH.getText()});
    }//GEN-LAST:event_TAMBAHActionPerformed

    private void KELUARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KELUARActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_KELUARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ALAMAT;
    private javax.swing.JLabel Awalan;
    private javax.swing.JLabel KELAS;
    private javax.swing.JButton KELUAR;
    private javax.swing.JLabel NAMA;
    private javax.swing.JLabel SEKOLAH;
    private javax.swing.JTextField TALAMAT;
    private javax.swing.JButton TAMBAH;
    private javax.swing.JTextField TANAM;
    private javax.swing.JComboBox<String> TKELAS;
    private javax.swing.JTextField TSEKOLAH;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
