/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihan_ukl;

/**
 *
 * @author H4NS
 */
public class Kuis_2 extends javax.swing.JFrame {

    /**
     * Creates new form Kuis_2
     */
    public Kuis_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HRG1 = new javax.swing.JPanel();
        Pembayaran = new javax.swing.JLabel();
        HARGA1 = new javax.swing.JLabel();
        HRG2 = new javax.swing.JLabel();
        HRG3 = new javax.swing.JLabel();
        HRG4 = new javax.swing.JLabel();
        Diskon = new javax.swing.JLabel();
        TH1 = new javax.swing.JTextField();
        TH2 = new javax.swing.JTextField();
        TH3 = new javax.swing.JTextField();
        TH4 = new javax.swing.JTextField();
        TD1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Proceed = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();
        Hapus = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        HRG1.setBackground(new java.awt.Color(204, 204, 0));

        Pembayaran.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        Pembayaran.setText("PEMBAYARAN");

        HARGA1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 16)); // NOI18N
        HARGA1.setText("Harga Barang 1");

        HRG2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 16)); // NOI18N
        HRG2.setText("Harga Barang 2");

        HRG3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        HRG3.setText("Harga Barang 3");

        HRG4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        HRG4.setText("Harga Barang 4");

        Diskon.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        Diskon.setText("Diskon");

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        jLabel2.setText("Total");

        Proceed.setText("Proceed");
        Proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProceedActionPerformed(evt);
            }
        });

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        Hapus.setText("Delete");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        Keluar.setText("Exit");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HRG1Layout = new javax.swing.GroupLayout(HRG1);
        HRG1.setLayout(HRG1Layout);
        HRG1Layout.setHorizontalGroup(
            HRG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HRG1Layout.createSequentialGroup()
                .addGroup(HRG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HRG1Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(Pembayaran))
                    .addGroup(HRG1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(HRG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(HRG1Layout.createSequentialGroup()
                                .addGroup(HRG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HARGA1)
                                    .addComponent(HRG2)
                                    .addComponent(HRG3)
                                    .addComponent(HRG4)
                                    .addComponent(Diskon)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(HRG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(HRG1Layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addGroup(HRG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TH1)
                                            .addComponent(TH2)
                                            .addComponent(TH3)
                                            .addComponent(TH4)
                                            .addComponent(TD1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)))
                                    .addGroup(HRG1Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(Proceed)
                                        .addGap(31, 31, 31)
                                        .addComponent(Hapus)
                                        .addGap(31, 31, 31)
                                        .addComponent(Keluar)))))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        HRG1Layout.setVerticalGroup(
            HRG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HRG1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Pembayaran)
                .addGap(38, 38, 38)
                .addGroup(HRG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HARGA1)
                    .addComponent(TH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HRG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HRG2)
                    .addComponent(TH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HRG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HRG3)
                    .addComponent(TH3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HRG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HRG4)
                    .addComponent(TH4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HRG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Diskon)
                    .addComponent(TD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(HRG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HRG1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2))
                    .addGroup(HRG1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(HRG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Proceed)
                            .addComponent(Hapus)
                            .addComponent(Keluar))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(HRG1);
        HRG1.setBounds(0, 0, 690, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProceedActionPerformed
        // TODO add your handling code here:
        int HARGA1 = Integer.parseInt(TH1.getText());
        int HRG2 = Integer.parseInt(TH2.getText());
        int HRG3 = Integer.parseInt(TH3.getText());
        int HRG4 = Integer.parseInt(TH4.getText());
        int Diskon = Integer.parseInt(TD1.getText());
        int total = HARGA1+HRG2+HRG3+HRG4;
        int diskon = (total-(total*Diskon/100));
        TA.setText("Harga Barang 1 :"+HARGA1+"\nHarga Barang 2 :"+HRG2+"\nHarga Barang 3 : "+HRG3+"\nHarga Barang 4 : "+HRG4+"\nTotal :"+total+"\nDiskon :"+Diskon+"%"+"\nJumlah Yang Perlu Di Bayar : "+diskon);
            
        
    }//GEN-LAST:event_ProceedActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
         TA.setText("");
        TH1.setText("");
        TH2.setText("");
        TH3.setText("");
        TH4.setText("");
        TD1.setText("");
    }//GEN-LAST:event_HapusActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_KeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kuis_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kuis_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kuis_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kuis_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kuis_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Diskon;
    private javax.swing.JLabel HARGA1;
    private javax.swing.JPanel HRG1;
    private javax.swing.JLabel HRG2;
    private javax.swing.JLabel HRG3;
    private javax.swing.JLabel HRG4;
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Keluar;
    private javax.swing.JLabel Pembayaran;
    private javax.swing.JButton Proceed;
    private javax.swing.JTextArea TA;
    private javax.swing.JTextField TD1;
    private javax.swing.JTextField TH1;
    private javax.swing.JTextField TH2;
    private javax.swing.JTextField TH3;
    private javax.swing.JTextField TH4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
