/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lathian3_part2;

import javax.swing.JOptionPane;

/**
 *
 * @author H4NS
 */
public class Latihan3 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan3
     */
    public Latihan3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        PANJANGBLK = new javax.swing.JLabel();
        LEBARBLK = new javax.swing.JLabel();
        TINGGIBLK = new javax.swing.JLabel();
        TPBLK = new javax.swing.JTextField();
        TLBLK = new javax.swing.JTextField();
        TTGBLK = new javax.swing.JTextField();
        HITUNG = new javax.swing.JButton();
        CMBLK1 = new javax.swing.JLabel();
        CMBLK2 = new javax.swing.JLabel();
        CMBLK3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PNJGKB = new javax.swing.JLabel();
        TPNJNGKB = new javax.swing.JTextField();
        KBCM = new javax.swing.JLabel();
        VLKB = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        JRBL = new javax.swing.JLabel();
        TJRBL = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        VLBL = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTabbedPane1.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N

        PANJANGBLK.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        PANJANGBLK.setText("Masukkan Panjang :");

        LEBARBLK.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        LEBARBLK.setText("Masukkan Lebar :");

        TINGGIBLK.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        TINGGIBLK.setText("Masukkan Tinggi :");

        HITUNG.setText("HITUNG");
        HITUNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HITUNGActionPerformed(evt);
            }
        });

        CMBLK1.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        CMBLK1.setText("CM");

        CMBLK2.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        CMBLK2.setText("CM");

        CMBLK3.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        CMBLK3.setText("CM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PANJANGBLK)
                                .addGap(18, 18, 18)
                                .addComponent(TPBLK, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LEBARBLK)
                                .addGap(28, 28, 28)
                                .addComponent(TLBLK, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 20, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(TINGGIBLK)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(HITUNG, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TTGBLK))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CMBLK1)
                    .addComponent(CMBLK2)
                    .addComponent(CMBLK3))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PANJANGBLK)
                    .addComponent(TPBLK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CMBLK1))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LEBARBLK)
                    .addComponent(TLBLK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CMBLK2))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CMBLK3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TINGGIBLK)
                            .addComponent(TTGBLK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addComponent(HITUNG, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Balok", jPanel1);

        PNJGKB.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        PNJGKB.setText("Masukkan Panjang Sisi");

        TPNJNGKB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPNJNGKBActionPerformed(evt);
            }
        });

        KBCM.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        KBCM.setText("CM");

        VLKB.setText("VOLUME");
        VLKB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VLKBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PNJGKB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TPNJNGKB))
                        .addGap(18, 18, 18)
                        .addComponent(KBCM))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(VLKB)))
                .addContainerGap(419, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(PNJGKB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TPNJNGKB, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KBCM))
                .addGap(15, 15, 15)
                .addComponent(VLKB)
                .addContainerGap(311, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Kubus", jPanel2);

        JRBL.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        JRBL.setText("Masukkan Panjang Jari-Jari");

        jLabel2.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        jLabel2.setText("CM");

        VLBL.setText("VOLUME");
        VLBL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VLBLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(TJRBL, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2))
                            .addComponent(JRBL)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(VLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(375, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(JRBL)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TJRBL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(VLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(302, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bola", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 70, 710, 500);

        jLabel1.setFont(new java.awt.Font("Monospaced", 3, 28)); // NOI18N
        jLabel1.setText("Program Pencari Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(31, 20, 640, 38);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TPNJNGKBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPNJNGKBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TPNJNGKBActionPerformed

    private void HITUNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HITUNGActionPerformed
        // TODO add your handling code here:
        int PANJANGBLK,LEBARBLK,TINGGIBLK;
        PANJANGBLK=Integer.parseInt(TPBLK.getText());
        LEBARBLK=Integer.parseInt(TLBLK.getText());
        TINGGIBLK=Integer.parseInt(TTGBLK.getText());
        int hasil=PANJANGBLK*LEBARBLK*TINGGIBLK;
        try{
            JOptionPane.showMessageDialog(null,"Volume Balok Adalah : "+hasil,"Luas",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Eror : "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
            
        }
        
        
    }//GEN-LAST:event_HITUNGActionPerformed

    private void VLKBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VLKBActionPerformed
        // TODO add your handling code here:
        int PNJGKB;
        PNJGKB=Integer.parseInt(TPNJNGKB.getText());
        int hasil=PNJGKB*PNJGKB*PNJGKB;
        try{
            JOptionPane.showMessageDialog(null,"Volume Kubus Adalah : "+hasil,"Luas",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Eror : "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_VLKBActionPerformed

    private void VLBLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VLBLActionPerformed
        // TODO add your handling code here:
        float JRBL;
        JRBL=Integer.parseInt(TJRBL.getText());
        float hasil1=(float)(4/3*3.14*JRBL*JRBL*JRBL);
        try{
            JOptionPane.showMessageDialog(null,"Luas Permukaan Bola Adalah : "+hasil1,"Luas ",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error : "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_VLBLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CMBLK1;
    private javax.swing.JLabel CMBLK2;
    private javax.swing.JLabel CMBLK3;
    private javax.swing.JButton HITUNG;
    private javax.swing.JLabel JRBL;
    private javax.swing.JLabel KBCM;
    private javax.swing.JLabel LEBARBLK;
    private javax.swing.JLabel PANJANGBLK;
    private javax.swing.JLabel PNJGKB;
    private javax.swing.JLabel TINGGIBLK;
    private javax.swing.JTextField TJRBL;
    private javax.swing.JTextField TLBLK;
    private javax.swing.JTextField TPBLK;
    private javax.swing.JTextField TPNJNGKB;
    private javax.swing.JTextField TTGBLK;
    private javax.swing.JButton VLBL;
    private javax.swing.JButton VLKB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
