/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LAtihan_Ukl2;

/**
 *
 * @author H4NS
 */
public class Latihan_Lanjutan extends javax.swing.JFrame {

    /**
     * Creates new form Latihan_Lanjutan
     */
    public Latihan_Lanjutan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Judul = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        Absen = new javax.swing.JLabel();
        Kelas = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        TN = new javax.swing.JTextField();
        TAB = new javax.swing.JTextField();
        Jurusan = new javax.swing.JLabel();
        RDB1 = new javax.swing.JRadioButton();
        RDB2 = new javax.swing.JRadioButton();
        Alamat = new javax.swing.JLabel();
        TALAM = new javax.swing.JTextField();
        Send = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        JUDUL = new javax.swing.JLabel();
        NAMA = new javax.swing.JLabel();
        ABSEN = new javax.swing.JLabel();
        KELAS = new javax.swing.JLabel();
        JURURSAN = new javax.swing.JLabel();
        ALAMAT = new javax.swing.JLabel();
        TANAM = new javax.swing.JTextField();
        TABSEN = new javax.swing.JTextField();
        PILIH = new javax.swing.JComboBox<>();
        RPL = new javax.swing.JRadioButton();
        TKJ = new javax.swing.JRadioButton();
        alamat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        KIRIM = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 178, 26));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        Judul.setFont(new java.awt.Font("Matura MT Script Capitals", 3, 24)); // NOI18N
        Judul.setText("BIODATA");

        Nama.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        Nama.setText("Nama");

        Absen.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        Absen.setText("Absen");

        Kelas.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        Kelas.setText("Kelas");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XI RPL 1", "XI RPL 2", "XI RPL 3", "XI RPL 4", "XI RPL 5", "XI RPL 6", "XI RPL 7", "XI TKJ 1", "XI TKJ 2", "XI TKJ 3", "XI TKJ 4", "XI TKJ 5", "XI TKJ 6", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        TN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNActionPerformed(evt);
            }
        });

        TAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TABActionPerformed(evt);
            }
        });

        Jurusan.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        Jurusan.setText("Jurusan");

        RDB1.setFont(new java.awt.Font("Monospaced", 3, 13)); // NOI18N
        RDB1.setText("RPL");

        RDB2.setFont(new java.awt.Font("Monospaced", 3, 13)); // NOI18N
        RDB2.setText("TKJ");

        Alamat.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        Alamat.setText("Alamat");

        TALAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TALAMActionPerformed(evt);
            }
        });

        Send.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        Send.setText("SEND");

        Exit.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        Exit.setText("Exit");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Kelas)
                    .addComponent(Nama)
                    .addComponent(Absen)
                    .addComponent(Jurusan)
                    .addComponent(Alamat))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TN)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(RDB1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                    .addComponent(RDB2)
                                    .addGap(11, 11, 11)))
                            .addComponent(TALAM, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TAB, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Judul)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Send)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                        .addComponent(Exit)
                        .addGap(129, 129, 129))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(Judul)
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nama)
                    .addComponent(TN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Absen)
                    .addComponent(TAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kelas)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RDB1)
                        .addComponent(RDB2))
                    .addComponent(Jurusan))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alamat)
                    .addComponent(TALAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Send)
                    .addComponent(Exit))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 660, 560);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 20, 24, 0);

        jPanel4.setBackground(new java.awt.Color(102, 102, 0));

        JUDUL.setFont(new java.awt.Font("Monospaced", 3, 30)); // NOI18N
        JUDUL.setForeground(new java.awt.Color(255, 255, 255));
        JUDUL.setText("BIODATA");

        NAMA.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        NAMA.setForeground(new java.awt.Color(255, 255, 255));
        NAMA.setText("NAMA");

        ABSEN.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        ABSEN.setForeground(new java.awt.Color(255, 255, 255));
        ABSEN.setText("ABSEN");

        KELAS.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        KELAS.setForeground(new java.awt.Color(255, 255, 255));
        KELAS.setText("KELAS");

        JURURSAN.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        JURURSAN.setForeground(new java.awt.Color(255, 255, 255));
        JURURSAN.setText("JURUSAN");

        ALAMAT.setFont(new java.awt.Font("Monospaced", 3, 16)); // NOI18N
        ALAMAT.setForeground(new java.awt.Color(255, 255, 255));
        ALAMAT.setText("ALAMAT");

        PILIH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XI RPL 1", "XI RPL 2", "XI RPL 3", "XI RPL 4", "XI RPL 5", "XI RPL 6", "XI RPL 7", "XI TKJ 1", "XI TKJ 2", "XI TKJ 3", "XI TKJ 4", "XI TKJ 5", "XI TKJ 6" }));
        PILIH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PILIHActionPerformed(evt);
            }
        });

        RPL.setText("RPL");

        TKJ.setText("TKJ");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LAtihan_Ukl2/90c41c49c5d6370b26e1db94ab74e244.jpg"))); // NOI18N

        KIRIM.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        KIRIM.setText("SEND");
        KIRIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KIRIMActionPerformed(evt);
            }
        });

        EXIT.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(JUDUL))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NAMA)
                                    .addComponent(JURURSAN)
                                    .addComponent(ABSEN)
                                    .addComponent(KELAS)
                                    .addComponent(ALAMAT))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TANAM)
                                    .addComponent(TABSEN)
                                    .addComponent(PILIH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(RPL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                        .addComponent(TKJ))
                                    .addComponent(alamat)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(KIRIM)
                                .addGap(102, 102, 102)
                                .addComponent(EXIT)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(163, 163, 163))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(JUDUL)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NAMA)
                            .addComponent(TANAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(ABSEN)
                                            .addComponent(TABSEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabel2)))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(KELAS)
                                    .addComponent(PILIH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JURURSAN)
                                    .addComponent(RPL)
                                    .addComponent(TKJ)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ALAMAT)
                                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(KIRIM)
                            .addComponent(EXIT))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 1090, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNActionPerformed

    private void TABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TABActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TABActionPerformed

    private void TALAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TALAMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TALAMActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void PILIHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PILIHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PILIHActionPerformed

    private void KIRIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KIRIMActionPerformed
        // TODO add your handling code here:
        String NAMA = TANAM.getText();
        String ABSEN = TABSEN.getText();
        String KELAS = PILIH.getSelectedItem().toString();
        String JURURSAN ="";
        String ALAMAT = alamat.getText();
        if(RPL.isSelected())
            JURURSAN ="RPL";
        else if (TKJ.isSelected())
            JURURSAN = "TKJ";
        else
            if(PILIH.getSelectedItem()=="XI RPL 1"){
                
            }
        if(PILIH.getSelectedItem()=="XI RPL 2"){
                
            }
        if(PILIH.getSelectedItem()=="XI RPL 3"){
                
            }
        if(PILIH.getSelectedItem()=="XI RPL 4"){
                
            }
        if(PILIH.getSelectedItem()=="XI RPL 5"){
                
            }
        if(PILIH.getSelectedItem()=="XI RPL 6"){
                
            }
        if(PILIH.getSelectedItem()=="XI TKJ 1"){
                
            }
         if(PILIH.getSelectedItem()=="XI TKJ 2"){
                
            }
          if(PILIH.getSelectedItem()=="XI TKJ 3"){
                
            }
           if(PILIH.getSelectedItem()=="XI TKJ 4"){
                
            }
            if(PILIH.getSelectedItem()=="XI TKJ 5"){
                
            }
             if(PILIH.getSelectedItem()=="XI TKJ 6"){
                
            }
             new Frame_Lanjutan(NAMA,ABSEN,KELAS,JURURSAN,ALAMAT).setVisible(true);





            
        
        
        
    }//GEN-LAST:event_KIRIMActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_EXITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan_Lanjutan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan_Lanjutan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan_Lanjutan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan_Lanjutan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan_Lanjutan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ABSEN;
    private javax.swing.JLabel ALAMAT;
    private javax.swing.JLabel Absen;
    private javax.swing.JLabel Alamat;
    private javax.swing.JButton EXIT;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel JUDUL;
    private javax.swing.JLabel JURURSAN;
    private javax.swing.JLabel Judul;
    private javax.swing.JLabel Jurusan;
    private javax.swing.JLabel KELAS;
    private javax.swing.JButton KIRIM;
    private javax.swing.JLabel Kelas;
    private javax.swing.JLabel NAMA;
    private javax.swing.JLabel Nama;
    private javax.swing.JComboBox<String> PILIH;
    private javax.swing.JRadioButton RDB1;
    private javax.swing.JRadioButton RDB2;
    private javax.swing.JRadioButton RPL;
    private javax.swing.JButton Send;
    private javax.swing.JTextField TAB;
    private javax.swing.JTextField TABSEN;
    private javax.swing.JTextField TALAM;
    private javax.swing.JTextField TANAM;
    private javax.swing.JRadioButton TKJ;
    private javax.swing.JTextField TN;
    private javax.swing.JTextField alamat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
